// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroLinea.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609061517_PruebaAvion")]
    partial class PruebaAvion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AeroLinea.Models.Consulta", b =>
                {
                    b.Property<int>("idConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idConsulta"));

                    b.Property<string>("descripcionConsultas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("motivoConsulta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("urgencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("idConsulta");

                    b.HasIndex("idUsuario");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("AeroLinea.Models.Flota", b =>
                {
                    b.Property<int>("idAvion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idAvion"));

                    b.Property<int>("capacidadAvion")
                        .HasColumnType("int");

                    b.Property<string>("claseAvion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fabricanteAvion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("matriculaAvion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("modeloAvion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("idAvion");

                    b.ToTable("Flota");
                });

            modelBuilder.Entity("AeroLinea.Models.Piloto", b =>
                {
                    b.Property<int>("idPiloto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idPiloto"));

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("apellidoPiloto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("fechaEmiLic")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("licenciaPiloto")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<DateTime>("nacimientoPiloto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombrePiloto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("telefonoPiloto")
                        .HasColumnType("int");

                    b.Property<string>("tipoLicPiloto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("idPiloto");

                    b.ToTable("Pilotos");
                });

            modelBuilder.Entity("AeroLinea.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("apellidosUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("contrasenaUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("correoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("discapacidad")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("esAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("identificacionUsuario")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("nacimientoUsuario")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombresUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("telefonoUsuario")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AeroLinea.Models.Consulta", b =>
                {
                    b.HasOne("AeroLinea.Models.Usuario", "Usuario")
                        .WithMany("Consultas")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AeroLinea.Models.Usuario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
