// <auto-generated />
using System;
using AeroLinea.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroLinea.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250427192021_Hola")]
    partial class Hola
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroLinea.Models.Pasajero", b =>
                {
                    b.Property<int>("idPasajero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPasajero"));

                    b.Property<string>("apellidosPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciudadOrigenPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoPostalPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dniPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimientoPasajero")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombresPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paisOrigenPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoPasajero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPasajero");

                    b.ToTable("Pasajeros");
                });
#pragma warning restore 612, 618
        }
    }
}
